
#__all__ = ['db2_oci_func']
import ctypes

from utils.logconfig import mylog

OCI_INVALID_HANDLE = ctypes.c_int(-2)

SQLCS_EXPLICIT =3
SQLCS_FLEXIBLE =4
SQLCS_IMPLICIT =1
SQLCS_LIT_NULL =5
SQLCS_NCHAR    =2
SQLT_AFC  =96
SQLT_AVC  =97
SQLT_BDOUBLE =22
SQLT_BFILEE =114
SQLT_BFILE = SQLT_BFILEE
SQLT_BFLOAT =21
SQLT_BIN  =23
SQLT_BLOB =113
SQLT_CFILEE =115
SQLT_CFILE =SQLT_CFILEE
SQLT_CHR  =1
SQLT_CLOB =112
SQLT_CUR  =102
SQLT_DAT  =12
SQLT_DATE                      =184
SQLT_FILE =SQLT_BFILEE
SQLT_FLT  =4
SQLT_IBDOUBLE =101
SQLT_IBFLOAT  =100
SQLT_INT  =3
SQLT_INTERVAL_DS               =190
SQLT_INTERVAL_YM               =189
SQLT_LAB  =105
SQLT_LBI  =24
SQLT_LNG  =8
SQLT_LVB  =95
SQLT_LVC  =94
SQLT_NCO  =122
SQLT_NON  =10
SQLT_NTY  =108
SQLT_NUM  =2
SQLT_ODT  =156
SQLT_OSL  =106
SQLT_PDN  =7
SQLT_PNTY =241
SQLT_RDD  =104
SQLT_REF  =110
SQLT_RID  =11
SQLT_RSET =116
SQLT_SLS  =91
SQLT_STR  =5
SQLT_TIME                      =185
SQLT_TIME_TZ                   =186
SQLT_TIMESTAMP                 =187
SQLT_TIMESTAMP_LTZ             =232
SQLT_TIMESTAMP_TZ              =188
SQLT_UIN  =68
SQLT_VBI  =15
SQLT_VCS  =9
SQLT_VNU  =6
SQLT_VST  =155


#define OCI_AC_DDL    0
#define OCI_AFC_PAD_ON      0x00008000
#define OCI_ALWAYS_BLOCKING 0x00000400
#define OCI_AQ_LAST_ACKNOWLEDGED 1
#define OCI_AQ_LAST_ENQUEUED     0
#define OCI_AQ_RESERVED_1      0x0002
#define OCI_AQ_RESERVED_2      0x0004
#define OCI_AQ_RESERVED_3      0x0008
#define OCI_AQ_RESERVED_4      0x0010
#define OCI_AQ_STREAMING_FLAG  0x02000000
#define OCI_ASM_VOLUME_SUPPORTED   1
#define OCI_ASM_VOLUME_UNSUPPORTED 0
#define OCI_ATCH_ENABLE_BEQ  0x4000
#define OCI_ATCH_RESERVED_1  0x0020
#define OCI_ATCH_RESERVED_2  0x0080
#define OCI_ATCH_RESERVED_3  0x0100
#define OCI_ATCH_RESERVED_4  0x0400
#define OCI_ATCH_RESERVED_5  0x2000
#define OCI_ATCH_RESERVED_6  0x8000
#define OCI_ATCH_RESERVED_7  0x10000
#define OCI_ATCH_RESERVED_8  0x20000
#define OCI_ATTR_ACCESS_BANNER              307
#define OCI_ATTR_ACTION                     367
#define OCI_ATTR_ACTION_CONTEXT             351
#define OCI_ATTR_ADMIN_PFILE                389
#define OCI_ATTR_AGENT_ADDRESS          65
#define OCI_ATTR_AGENT_NAME             64
#define OCI_ATTR_AGENT_PROTOCOL         66
#define OCI_ATTR_ALLOC_DURATION 37
#define OCI_ATTR_APPCTX_ATTR               276
#define OCI_ATTR_APPCTX_LIST               274
#define OCI_ATTR_APPCTX_NAME               275
#define OCI_ATTR_APPCTX_SIZE               273
#define OCI_ATTR_APPCTX_VALUE              277
#define OCI_ATTR_AQ_ERROR_INDEX         OCI_ATTR_DML_ROW_OFFSET
#define OCI_ATTR_AQ_NTFN_GROUPING_COUNT            237
#define OCI_ATTR_AQ_NTFN_GROUPING_MSGID_ARRAY      236
#define OCI_ATTR_AQ_NUM_ERRORS          OCI_ATTR_NUM_DML_ERRORS
#define OCI_ATTR_ASM_VOL_SPRT               205
#define OCI_ATTR_ATTEMPTS               59
#define OCI_ATTR_AUDIT_BANNER               308
#define OCI_ATTR_AUDIT_SESSION_ID           362
#define OCI_ATTR_AUTOCOMMIT_DDL            271
#define OCI_ATTR_BIND_COUNT                 190
#define OCI_ATTR_BIND_DN         155
#define OCI_ATTR_BIND_ROWCBK                301
#define OCI_ATTR_BIND_ROWCTX                302
#define OCI_ATTR_BUF_ADDR               76
#define OCI_ATTR_BUF_SIZE               77
#define OCI_ATTR_CACHE            115
#define OCI_ATTR_CACHE_CLIENT_CONTEXT      251
#define OCI_ATTR_CACHE_MAX_SIZE 35
#define OCI_ATTR_CACHE_OPT_SIZE 34
#define OCI_ATTR_CALL_TIME                  370
#define OCI_ATTR_CANONICAL_ALGO             171
#define OCI_ATTR_CATALOG_LOCATION          268
#define OCI_ATTR_CERTIFICATE                169
#define OCI_ATTR_CHAR_COUNT  15
#define OCI_ATTR_CHAR_SIZE                 286
#define OCI_ATTR_CHAR_USED                 285
#define OCI_ATTR_CHARSET  20
#define OCI_ATTR_CHARSET_FORM 32
#define OCI_ATTR_CHARSET_ID 31
#define OCI_ATTR_CHDES_DBNAME            405
#define OCI_ATTR_CHDES_NFYTYPE           406
#define OCI_ATTR_CHDES_QUERIES 425
#define OCI_ATTR_CHDES_ROW_OPFLAGS       413
#define OCI_ATTR_CHDES_ROW_ROWID         412
#define OCI_ATTR_CHDES_TABLE_CHANGES     408
#define OCI_ATTR_CHDES_TABLE_NAME        409
#define OCI_ATTR_CHDES_TABLE_OPFLAGS     410
#define OCI_ATTR_CHDES_TABLE_ROW_CHANGES 411
#define OCI_ATTR_CHDES_XID               407
#define OCI_ATTR_CHNF_CHANGELAG           404
#define OCI_ATTR_CHNF_OPERATIONS          403
#define OCI_ATTR_CHNF_REGHANDLE          414
#define OCI_ATTR_CHNF_ROWIDS              402
#define OCI_ATTR_CHNF_TABLENAMES          401
#define OCI_ATTR_CLIENT_IDENTIFIER         278
#define OCI_ATTR_CLIENT_INFO                368
#define OCI_ATTR_CLUSTERED        105
#define OCI_ATTR_COL_COUNT              82
#define OCI_ATTR_COL_ENC        102
#define OCI_ATTR_COL_ENC_SALT   103
#define OCI_ATTR_COLLECT_CALL_TIME          369
#define OCI_ATTR_COLLECTION_ELEMENT        227
#define OCI_ATTR_COLLECTION_TYPECODE       217
#define OCI_ATTR_COMMENT                    343
#define OCI_ATTR_COMPLEXOBJECT_COLL_OUTOFLINE   53
#define OCI_ATTR_COMPLEXOBJECT_LEVEL            52
#define OCI_ATTR_COMPLEXOBJECTCOMP_TYPE         50
#define OCI_ATTR_COMPLEXOBJECTCOMP_TYPE_LEVEL   51
#define OCI_ATTR_CONDITION                  342
#define OCI_ATTR_CONN_BUSY_COUNT            179
#define OCI_ATTR_CONN_INCR                  185
#define OCI_ATTR_CONN_MAX                   184
#define OCI_ATTR_CONN_MIN                   183
#define OCI_ATTR_CONN_NOWAIT               178
#define OCI_ATTR_CONN_OPEN_COUNT            180
#define OCI_ATTR_CONN_TIMEOUT               181
#define OCI_ATTR_CONNECTION_CLASS  425
#define OCI_ATTR_CONSUMER_NAME          50
#define OCI_ATTR_CORRELATION            58
#define OCI_ATTR_CQ_QUERYID               304
#define OCI_ATTR_CQDES_OPERATION 422
#define OCI_ATTR_CQDES_QUERYID 424
#define OCI_ATTR_CQDES_TABLE_CHANGES 423
#define OCI_ATTR_CURRENT_ERRCOL            2003
#define OCI_ATTR_CURRENT_POSITION           164
#define OCI_ATTR_CURRENT_SCHEMA             224
#define OCI_ATTR_CURSOR_COMMIT_BEHAVIOR    266
#define OCI_ATTR_DATA_SIZE      1
#define OCI_ATTR_DATA_TYPE      2
#define OCI_ATTR_DATEFORMAT             75
#define OCI_ATTR_DB_CHARSET_ID     416
#define OCI_ATTR_DB_NCHARSET_ID    417
#define OCI_ATTR_DBDOMAIN         399
#define OCI_ATTR_DBNAME           391
#define OCI_ATTR_DEFAULT_LOBPREFETCH_SIZE     438
#define OCI_ATTR_DELAY                  56
#define OCI_ATTR_DEQ_MODE               51
#define OCI_ATTR_DEQ_MSGID              54
#define OCI_ATTR_DEQCOND                    146
#define OCI_ATTR_DESC_PUBLIC               250
#define OCI_ATTR_DESC_SYNBASE              284
#define OCI_ATTR_DESCRIBE_NATIVE            189
#define OCI_ATTR_DIGEST_ALGO                168
#define OCI_ATTR_DIGEST_VALUE               173
#define OCI_ATTR_DIRPATH_BADROW             329
#define OCI_ATTR_DIRPATH_BADROW_LENGTH      330
#define OCI_ATTR_DIRPATH_CONVERT            328
#define OCI_ATTR_DIRPATH_DCACHE_DISABLE     307
#define OCI_ATTR_DIRPATH_DCACHE_HITS        306
#define OCI_ATTR_DIRPATH_DCACHE_MISSES      305
#define OCI_ATTR_DIRPATH_DCACHE_NUM         303
#define OCI_ATTR_DIRPATH_DCACHE_SIZE        304
#define OCI_ATTR_DIRPATH_EXPR_TYPE  150
#define OCI_ATTR_DIRPATH_FILE               139
#define OCI_ATTR_DIRPATH_FN_CTX             167
#define OCI_ATTR_DIRPATH_GRANULE_OFFSET     333
#define OCI_ATTR_DIRPATH_GRANULE_SIZE       332
#define OCI_ATTR_DIRPATH_INDEX_MAINT_METHOD 138
#define OCI_ATTR_DIRPATH_INPUT         151
#define OCI_ATTR_DIRPATH_LOCK_WAIT          359
#define OCI_ATTR_DIRPATH_MODE           78
#define OCI_ATTR_DIRPATH_NOLOG          79
#define OCI_ATTR_DIRPATH_OBJ_CONSTR         206
#define OCI_ATTR_DIRPATH_OID                187
#define OCI_ATTR_DIRPATH_PARALLEL       80
#define OCI_ATTR_DIRPATH_RESERVED_1         334
#define OCI_ATTR_DIRPATH_RESERVED_10       2001
#define OCI_ATTR_DIRPATH_RESERVED_11       2002
#define OCI_ATTR_DIRPATH_RESERVED_12       2005
#define OCI_ATTR_DIRPATH_RESERVED_13       2006
#define OCI_ATTR_DIRPATH_RESERVED_14       2007
#define OCI_ATTR_DIRPATH_RESERVED_15       2008
#define OCI_ATTR_DIRPATH_RESERVED_16       2009
#define OCI_ATTR_DIRPATH_RESERVED_17       2010
#define OCI_ATTR_DIRPATH_RESERVED_18       2011
#define OCI_ATTR_DIRPATH_RESERVED_19       2012
#define OCI_ATTR_DIRPATH_RESERVED_2         335
#define OCI_ATTR_DIRPATH_RESERVED_3         337
#define OCI_ATTR_DIRPATH_RESERVED_4         338
#define OCI_ATTR_DIRPATH_RESERVED_5         357
#define OCI_ATTR_DIRPATH_RESERVED_6         358
#define OCI_ATTR_DIRPATH_RESERVED_7         326
#define OCI_ATTR_DIRPATH_RESERVED_8         327
#define OCI_ATTR_DIRPATH_RESERVED_9        2000
#define OCI_ATTR_DIRPATH_SID                194
#define OCI_ATTR_DIRPATH_SKIPINDEX_METHOD   145
#define OCI_ATTR_DIRPATH_SORTED_INDEX    137
#define OCI_ATTR_DIRPATH_STORAGE_INITIAL    140
#define OCI_ATTR_DIRPATH_STORAGE_NEXT       141
#define OCI_ATTR_DIRPATH_STREAM_VERSION     212
#define OCI_ATTR_DIRPATH_SUBTYPE_INDEX     2004
#define OCI_ATTR_DIRPATH_WRITE_ORDER        331
#define OCI_ATTR_DISP_NAME      100
#define OCI_ATTR_DISP_SIZE      3
#define OCI_ATTR_DISTINGUISHED_NAME        300
#define OCI_ATTR_DML_ROW_OFFSET         74
#define OCI_ATTR_DN_COUNT        161
#define OCI_ATTR_DRIVER_NAME                424
#define OCI_ATTR_DURATION         132
#define OCI_ATTR_ECONTEXT_ID                371
#define OCI_ATTR_ECONTEXT_SEQ               372
#define OCI_ATTR_EDITION                   288
#define OCI_ATTR_ENCAPSULATION             235
#define OCI_ATTR_ENCC_SIZE      101
#define OCI_ATTR_ENQ_TIME               62
#define OCI_ATTR_ENV  5
#define OCI_ATTR_ENV_CHARSET_ID   OCI_ATTR_CHARSET_ID
#define OCI_ATTR_ENV_NCHARSET_ID  OCI_ATTR_NCHARSET_ID
#define OCI_ATTR_ENV_UTF16                  209
#define OCI_ATTR_ERRONEOUS_COLUMN           203
#define OCI_ATTR_EVAL_CONTEXT_NAME          346
#define OCI_ATTR_EVAL_CONTEXT_OWNER         345
#define OCI_ATTR_EVALUATION_FUNCTION        347
#define OCI_ATTR_EVENTTYPE        400
#define OCI_ATTR_EVTCBK                     304
#define OCI_ATTR_EVTCTX                     305
#define OCI_ATTR_EXCEPTION_QUEUE        61
#define OCI_ATTR_EXPIRATION             57
#define OCI_ATTR_EXTERNAL_NAME   26
#define OCI_ATTR_FDO          39
#define OCI_ATTR_FETCH_ROWID                 448
#define OCI_ATTR_FLOW_CONTROL_TIMEOUT       423
#define OCI_ATTR_FNCODE  1
#define OCI_ATTR_FOCBK        43
#define OCI_ATTR_FSPRECISION OCI_ATTR_PDSCL
#define OCI_ATTR_HA_SOURCE        401
#define OCI_ATTR_HA_SRVFIRST      403
#define OCI_ATTR_HA_SRVNEXT       404
#define OCI_ATTR_HA_STATUS        402
#define OCI_ATTR_HA_TIMESTAMP     395
#define OCI_ATTR_HANDLE_POSITION            191
#define OCI_ATTR_HAS_DEFAULT    212
#define OCI_ATTR_HAS_FILE                  226
#define OCI_ATTR_HAS_LOB                   225
#define OCI_ATTR_HAS_NESTED_TABLE          224
#define OCI_ATTR_HAS_RESULT                240
#define OCI_ATTR_HAS_SUBTYPES        321
#define OCI_ATTR_HEAPALLOC 30
#define OCI_ATTR_HOSTNAME         390
#define OCI_ATTR_HW_MARK          117
#define OCI_ATTR_IN_V8_MODE   44
#define OCI_ATTR_INCR             114
#define OCI_ATTR_INDEX_ONLY       107
#define OCI_ATTR_INITIAL_CLIENT_ROLES  100
#define OCI_ATTR_INST_TYPE                  207
#define OCI_ATTR_INSTNAME         392
#define OCI_ATTR_INSTSTARTTIME    394
#define OCI_ATTR_INTERNAL_NAME   25
#define OCI_ATTR_IOMODE         213
#define OCI_ATTR_IS_CONSTANT               239
#define OCI_ATTR_IS_CONSTRUCTOR            241
#define OCI_ATTR_IS_DESTRUCTOR             242
#define OCI_ATTR_IS_EXTERNAL                216
#define OCI_ATTR_IS_FINAL_METHOD           281
#define OCI_ATTR_IS_FINAL_TYPE             279
#define OCI_ATTR_IS_INCOMPLETE_TYPE        219
#define OCI_ATTR_IS_INLINE                 238
#define OCI_ATTR_IS_INSTANTIABLE_METHOD    282
#define OCI_ATTR_IS_INSTANTIABLE_TYPE      280
#define OCI_ATTR_IS_INVOKER_RIGHTS 133
#define OCI_ATTR_IS_JAVA_TYPE              287
#define OCI_ATTR_IS_MAP                    244
#define OCI_ATTR_IS_NULL        7
#define OCI_ATTR_IS_OPERATOR               243
#define OCI_ATTR_IS_ORDER                  245
#define OCI_ATTR_IS_OVERRIDDEN_METHOD 325
#define OCI_ATTR_IS_OVERRIDING_METHOD      283
#define OCI_ATTR_IS_PREDEFINED_TYPE        221
#define OCI_ATTR_IS_RNDS                   246
#define OCI_ATTR_IS_RNPS                   247
#define OCI_ATTR_IS_SELFISH                236
#define OCI_ATTR_IS_SUBTYPE                258
#define OCI_ATTR_IS_SYSTEM_GENERATED_TYPE  223
#define OCI_ATTR_IS_SYSTEM_TYPE            220
#define OCI_ATTR_IS_TEMPORARY     130
#define OCI_ATTR_IS_TRANSIENT_TYPE         222
#define OCI_ATTR_IS_TYPED         131
#define OCI_ATTR_IS_VIRTUAL                237
#define OCI_ATTR_IS_WNDS                   248
#define OCI_ATTR_IS_WNPS                   249
#define OCI_ATTR_IS_XMLTYPE          315
#define OCI_ATTR_KERBEROS_CID               341
#define OCI_ATTR_KERBEROS_CID_KEY           364
#define OCI_ATTR_KERBEROS_KEY               363
#define OCI_ATTR_KERBEROS_TICKET           301
#define OCI_ATTR_LDAP_AUTH       158
#define OCI_ATTR_LDAP_CRED       156
#define OCI_ATTR_LDAP_CTX        159
#define OCI_ATTR_LDAP_HOST       153
#define OCI_ATTR_LDAP_PORT       154
#define OCI_ATTR_LEVEL          211
#define OCI_ATTR_LFPRECISION OCI_ATTR_PDPRC
#define OCI_ATTR_LINK             111
#define OCI_ATTR_LIST_ARGUMENTS   108
#define OCI_ATTR_LIST_COLUMNS     103
#define OCI_ATTR_LIST_OBJECTS              261
#define OCI_ATTR_LIST_SCHEMAS              263
#define OCI_ATTR_LIST_SUBPROGRAMS 109
#define OCI_ATTR_LIST_SUBTYPES       323
#define OCI_ATTR_LIST_TABLE_ALIASES         352
#define OCI_ATTR_LIST_TYPE_ATTRS           229
#define OCI_ATTR_LIST_TYPE_METHODS         231
#define OCI_ATTR_LIST_VARIABLE_TYPES        353
#define OCI_ATTR_LOB_REGION_MIME          447
#define OCI_ATTR_LOB_REGION_OFFSET        445
#define OCI_ATTR_LOB_REGION_PRIMARY       442
#define OCI_ATTR_LOB_REGION_PRIMOFF       443
#define OCI_ATTR_LOB_REGIOnLen        446
#define OCI_ATTR_LOBEMPTY     45
#define OCI_ATTR_LOBPREFETCH_LENGTH           440
#define OCI_ATTR_LOBPREFETCH_SIZE             439
#define OCI_ATTR_LOCKING_MODE              272
#define OCI_ATTR_LTYPE            128
#define OCI_ATTR_MAP_METHOD                232
#define OCI_ATTR_MAX              113
#define OCI_ATTR_MAX_CATALOG_NAMELEN       267
#define OCI_ATTR_MAX_COLUMN_LEN            265
#define OCI_ATTR_MAX_PROC_LEN              264
#define OCI_ATTR_MAXCHAR_SIZE               163
#define OCI_ATTR_MAXDATA_SIZE 33
#define OCI_ATTR_MEMPOOL_APPNAME        90
#define OCI_ATTR_MEMPOOL_HOMENAME       91
#define OCI_ATTR_MEMPOOL_INSTNAME       89
#define OCI_ATTR_MEMPOOL_MODEL          92
#define OCI_ATTR_MEMPOOL_SIZE           88
#define OCI_ATTR_MESSAGE_CSCN               360
#define OCI_ATTR_MESSAGE_DSCN               361
#define OCI_ATTR_MIGSESSION             86
#define OCI_ATTR_MIN              112
#define OCI_ATTR_MODES                  93
#define OCI_ATTR_MODULE                     366
#define OCI_ATTR_MSG_DELIVERY_MODE 407
#define OCI_ATTR_MSG_PROP               72
#define OCI_ATTR_MSG_STATE              63
#define OCI_ATTR_NAME           4
#define OCI_ATTR_NAVIGATION             52
#define OCI_ATTR_NCHAR   21
#define OCI_ATTR_NCHARSET_ID               262
#define OCI_ATTR_NESTED_PREFETCH_MEMORY 14
#define OCI_ATTR_NESTED_PREFETCH_ROWS 12
#define OCI_ATTR_NETWORK_FILE_DESC       415
#define OCI_ATTR_NFY_FLAGS        406
#define OCI_ATTR_NFY_MSGID              71
#define OCI_ATTR_NOCACHE                87
#define OCI_ATTR_NONBLOCKING_MODE  3
#define OCI_ATTR_NOWAIT_SUPPORT            270
#define OCI_ATTR_NUM_ARGS       215
#define OCI_ATTR_NUM_ATTRS        120
#define OCI_ATTR_NUM_COLS         102
#define OCI_ATTR_NUM_DML_ERRORS         73
#define OCI_ATTR_NUM_OPEN_STMTS             188
#define OCI_ATTR_NUM_PARAMS       121
#define OCI_ATTR_NUM_ROWS               81
#define OCI_ATTR_NUM_SUBTYPES        322
#define OCI_ATTR_NUM_TYPE_ATTRS            228
#define OCI_ATTR_NUM_TYPE_METHODS          230
#define OCI_ATTR_numElements                 234
#define OCI_ATTR_OBJ_ID           136
#define OCI_ATTR_OBJ_NAME         134
#define OCI_ATTR_OBJ_SCHEMA       135
#define OCI_ATTR_OBJ_SUBS                   336
#define OCI_ATTR_OBJECT   2
#define OCI_ATTR_OBJID            122
#define OCI_ATTR_ORA_DEBUG_JDWP            302
#define OCI_ATTR_ORDER            116
#define OCI_ATTR_ORDER_METHOD              233
#define OCI_ATTR_ORIGINAL_MSGID         69
#define OCI_ATTR_OVERLOAD       210
#define OCI_ATTR_OVERLOAD_ID      125
#define OCI_ATTR_PARAM            124
#define OCI_ATTR_PARAM_COUNT 18
#define OCI_ATTR_PARSE_ERROR_OFFSET 129
#define OCI_ATTR_PARTITIONED      106
#define OCI_ATTR_PASSWORD 23
#define OCI_ATTR_PDPRC   17
#define OCI_ATTR_PDSCL   16
#define OCI_ATTR_pinDur 38
#define OCI_ATTR_PINOPTION 36
#define OCI_ATTR_POSITION       11
#define OCI_ATTR_POSTPROCESSING_CALLBACK 40
#define OCI_ATTR_POSTPROCESSING_CONTEXT 41
#define OCI_ATTR_PRECISION      5
#define OCI_ATTR_PREFETCH_MEMORY 13
#define OCI_ATTR_PREFETCH_ROWS  11
#define OCI_ATTR_PRIORITY               55
#define OCI_ATTR_PRIVATE_KEY                172
#define OCI_ATTR_PROXY_CLIENT            416
#define OCI_ATTR_PROXY_CREDENTIALS      99
#define OCI_ATTR_PTYPE            123
#define OCI_ATTR_PURITY            426
#define OCI_ATTR_PURITY_DEFAULT    0x00
#define OCI_ATTR_PURITY_NEW        0x01
#define OCI_ATTR_PURITY_SELF       0x02
#define OCI_ATTR_QUEUE_NAME             70
#define OCI_ATTR_RADIX          214
#define OCI_ATTR_RDBA             104
#define OCI_ATTR_READONLY_TXN               201
#define OCI_ATTR_RECEIVE_TIMEOUT            436
#define OCI_ATTR_RECIPIENT_LIST         60
#define OCI_ATTR_REF_TDO          110
#define OCI_ATTR_RELATIVE_MSGID         48
#define OCI_ATTR_RESERVED_10                211
#define OCI_ATTR_RESERVED_12                214
#define OCI_ATTR_RESERVED_13                215
#define OCI_ATTR_RESERVED_14               303
#define OCI_ATTR_RESERVED_15                217
#define OCI_ATTR_RESERVED_16                219
#define OCI_ATTR_RESERVED_17                220
#define OCI_ATTR_RESERVED_18                221
#define OCI_ATTR_RESERVED_19                222
#define OCI_ATTR_RESERVED_2                 147
#define OCI_ATTR_RESERVED_20                223
#define OCI_ATTR_RESERVED_21                415
#define OCI_ATTR_RESERVED_22      396
#define OCI_ATTR_RESERVED_23      397
#define OCI_ATTR_RESERVED_24      398
#define OCI_ATTR_RESERVED_25       418
#define OCI_ATTR_RESERVED_26                422
#define OCI_ATTR_RESERVED_27      425
#define OCI_ATTR_RESERVED_28               426
#define OCI_ATTR_RESERVED_29               427
#define OCI_ATTR_RESERVED_3                 165
#define OCI_ATTR_RESERVED_30               428
#define OCI_ATTR_RESERVED_31               429
#define OCI_ATTR_RESERVED_32               430
#define OCI_ATTR_RESERVED_33               433
#define OCI_ATTR_RESERVED_34               434
#define OCI_ATTR_RESERVED_35                437
#define OCI_ATTR_RESERVED_36               444
#define OCI_ATTR_RESERVED_37              449
#define OCI_ATTR_RESERVED_4                 166
#define OCI_ATTR_RESERVED_41               454
#define OCI_ATTR_RESERVED_5                 192
#define OCI_ATTR_RESERVED_6                 200
#define OCI_ATTR_RESERVED_7                 202
#define OCI_ATTR_RESERVED_8                 204
#define OCI_ATTR_RESERVED_9                 210
#define OCI_ATTR_ROW_COUNT   9
#define OCI_ATTR_ROWID   19
#define OCI_ATTR_ROWS_FETCHED               197
#define OCI_ATTR_ROWS_RETURNED 42
#define OCI_ATTR_SAVEPOINT_SUPPORT         269
#define OCI_ATTR_SCALE          6
#define OCI_ATTR_SCHEMA_NAME    9
#define OCI_ATTR_SCN_BASE                   198
#define OCI_ATTR_SCN_WRAP                   199
#define OCI_ATTR_SEND_TIMEOUT               435
#define OCI_ATTR_SENDER_ID              68
#define OCI_ATTR_SEQUENCE_DEVIATION     49
#define OCI_ATTR_SERVER 6
#define OCI_ATTR_SERVER_BUSY                193
#define OCI_ATTR_SERVER_DN       162
#define OCI_ATTR_SERVER_DNS      160
#define OCI_ATTR_SERVER_GROUP           85
#define OCI_ATTR_SERVER_STATUS              143
#define OCI_ATTR_SERVICENAME      393
#define OCI_ATTR_SESSION 7
#define OCI_ATTR_SESSION_MIGRATED           377
#define OCI_ATTR_SESSION_PRESERVE_STATE     388
#define OCI_ATTR_SESSION_STATE              373
#define OCI_ATTR_SESSION_STATE_CLEARED      376
#define OCI_ATTR_SESSION_STATETYPE          374
#define OCI_ATTR_SESSLANG     46
#define OCI_ATTR_SHARED_HEAPALLOC       84
#define OCI_ATTR_SIGNATURE                  175
#define OCI_ATTR_SIGNATURE_ALGO             170
#define OCI_ATTR_SIGNATURE_VAL              174
#define OCI_ATTR_SKIP_BUFFER                303
#define OCI_ATTR_SPOOL_BUSY_COUNT           310
#define OCI_ATTR_SPOOL_GETMODE              309
#define OCI_ATTR_SPOOL_INCR                 314
#define OCI_ATTR_SPOOL_MAX                  313
#define OCI_ATTR_SPOOL_MIN                  312
#define OCI_ATTR_SPOOL_OPEN_COUNT           311
#define OCI_ATTR_SPOOL_STMTCACHESIZE        208
#define OCI_ATTR_SPOOL_TIMEOUT              308
#define OCI_ATTR_SQLCODE  4
#define OCI_ATTR_SQLFNCODE 10
#define OCI_ATTR_STATEMENT                  144
#define OCI_ATTR_STMT_IS_RETURNING          218
#define OCI_ATTR_STMT_STATE                 182
#define OCI_ATTR_STMT_TYPE   24
#define OCI_ATTR_STMTCACHE_CBK              421
#define OCI_ATTR_STMTCACHE_CBKCTX           420
#define OCI_ATTR_STMTCACHESIZE              176
#define OCI_ATTR_STREAM_OFFSET          83
#define OCI_ATTR_SUB_NAME       10
#define OCI_ATTR_SUBSCR_CALLBACK        95
#define OCI_ATTR_SUBSCR_CQ_QOSFLAGS         229
#define OCI_ATTR_SUBSCR_CQ_REGID            230
#define OCI_ATTR_SUBSCR_CTX             96
#define OCI_ATTR_SUBSCR_NAME            94
#define OCI_ATTR_SUBSCR_NAMESPACE       98
#define OCI_ATTR_SUBSCR_NAMESPACE_CTX       228
#define OCI_ATTR_SUBSCR_NTFN_GROUPING_CLASS        231
#define OCI_ATTR_SUBSCR_NTFN_GROUPING_REPEAT_COUNT 235
#define OCI_ATTR_SUBSCR_NTFN_GROUPING_START_TIME   234
#define OCI_ATTR_SUBSCR_NTFN_GROUPING_TYPE         233
#define OCI_ATTR_SUBSCR_NTFN_GROUPING_VALUE        232
#define OCI_ATTR_SUBSCR_PAYLOAD         97
#define OCI_ATTR_SUBSCR_PAYLOADCBK          226
#define OCI_ATTR_SUBSCR_PORTNO              390
#define OCI_ATTR_SUBSCR_QOSFLAGS            225
#define OCI_ATTR_SUBSCR_RECPT               148
#define OCI_ATTR_SUBSCR_RECPTPRES           195
#define OCI_ATTR_SUBSCR_RECPTPROTO          149
#define OCI_ATTR_SUBSCR_TIMEOUT             227
#define OCI_ATTR_SUPERTYPE_NAME            260
#define OCI_ATTR_SUPERTYPE_SCHEMA_NAME     259
#define OCI_ATTR_TABLE_ENC         41
#define OCI_ATTR_TABLE_ENC_ALG     418
#define OCI_ATTR_TABLE_ENC_ALG_ID  419
#define OCI_ATTR_TABLE_NAME                 356
#define OCI_ATTR_TABLESPACE       126
#define OCI_ATTR_TAF_ENABLED      405
#define OCI_ATTR_TDO              127
#define OCI_ATTR_TIMESTAMP        119
#define OCI_ATTR_TRANS   8
#define OCI_ATTR_TRANS_LOCK 28
#define OCI_ATTR_TRANS_NAME 29
#define OCI_ATTR_TRANS_TIMEOUT              142
#define OCI_ATTR_TRANSACTION_NO             365
#define OCI_ATTR_TRANSFORMATION             196
#define OCI_ATTR_TYPE_NAME      8
#define OCI_ATTR_TYPE_SCHEMA      118
#define OCI_ATTR_TYPECODE                  216
#define OCI_ATTR_UCI_CONSTRUCT             252
#define OCI_ATTR_UCI_COPY                  254
#define OCI_ATTR_UCI_DESTRUCT              253
#define OCI_ATTR_UCI_PICKLE                255
#define OCI_ATTR_UCI_REFRESH               257
#define OCI_ATTR_UCI_UNPICKLE              256
#define OCI_ATTR_UNK              101
#define OCI_ATTR_USER_MEMORY               306
#define OCI_ATTR_USER_PROPERTY          67
#define OCI_ATTR_USERNAME 22
#define OCI_ATTR_VALUE                      344
#define OCI_ATTR_VAR_METHOD_FUNCTION        350
#define OCI_ATTR_VAR_TYPE                   348
#define OCI_ATTR_VAR_VALUE_FUNCTION         349
#define OCI_ATTR_VERSION                   218
#define OCI_ATTR_VISIBILITY             47
#define OCI_ATTR_WAIT                   53
#define OCI_ATTR_WALL_LOC        157
#define OCI_ATTR_XADFIELD_RESERVED_1        339
#define OCI_ATTR_XADFIELD_RESERVED_2        340
#define OCI_ATTR_XID     27
#define OCI_ATTR_XML_HRCHY_ENABLED   324
#define OCI_ATTR_XMLELEMENT_NAME     317
#define OCI_ATTR_XMLpTypeStored_OBJ  320
#define OCI_ATTR_XMLSCHEMA_NAME      316
#define OCI_ATTR_XMLSQLTYPE_NAME     319
#define OCI_ATTR_XMLSQLTYPSCH_NAME   318
#define OCI_ATTR_XMLTYPE_BINARY_XML  422
#define OCI_AUTH         0x08
#define OCI_AUTH_RESERVED_1 0x00000020
#define OCI_AUTH_RESERVED_2 0x00000400
#define OCI_AUTH_RESERVED_3 0x00000800
#define OCI_AUTH_RESERVED_4 0x00001000
#define OCI_AUTH_RESERVED_5 0x00002000
#define OCI_AUTH_RESERVED_6 0x00010000
#define OCI_BATCH_ERRORS           0x00000080
#define OCI_BATCH_MODE             0x00000001
#define OCI_BIND_RESERVED_2   0x00000010
#define OCI_BIND_RESERVED_3   0x00000100
#define OCI_BIND_SOFT         0x00000040
#define OCI_CBK_STMTCACHE_STMTPURGE  0x01
#define OCI_CL_END   1
#define OCI_CL_START 0
#define OCI_CLIENT_STATS    0x10
#define OCI_COMMIT_ON_SUCCESS      0x00000020
#define OCI_CONTINUE -24200
OCI_CPOOL            = 0x0200
#define OCI_CPOOL_REINITIALIZE 0x111
#define OCI_CRED_EXT        2
#define OCI_CRED_PROXY      3
#define OCI_CRED_RDBMS      1
#define OCI_CRED_RESERVED_1 4
#define OCI_CRED_RESERVED_2 5
#define OCI_CURSOR_CLOSED 1
#define OCI_CURSOR_OPEN   0
#define OCI_DATA_AT_EXEC      0x00000002
OCI_DEFAULT                 =  0x00000000
OCI_DEFINE_RESERVED_1       =  0x00000008
#define OCI_DEFINE_RESERVED_2 0x00000020
#define OCI_DEFINE_SOFT       0x00000080
#define OCI_DEQ_BROWSE          1
#define OCI_DEQ_FIRST_MSG        1
#define OCI_DEQ_GETSIG          5
#define OCI_DEQ_IMMEDIATE       1
#define OCI_DEQ_LOCKED          2
#define OCI_DEQ_MULT_TRANSACTION 5
#define OCI_DEQ_NEXT_MSG         3
#define OCI_DEQ_NEXT_TRANSACTION 2
#define OCI_DEQ_NO_WAIT         0
#define OCI_DEQ_ON_COMMIT       2
#define OCI_DEQ_REMOVE          3
#define OCI_DEQ_REMOVE_NODATA   4
#define OCI_DEQ_RESERVED_1      0x000001
#define OCI_DEQ_WAIT_FOREVER    -1
#define OCI_DESC_RESERVED_1        0x00001000
#define OCI_DESCRIBE_ONLY          0x00000010
#define OCI_DIRPATH_INPUT_OCI         0x04
#define OCI_DIRPATH_INPUT_STREAM      0x02
#define OCI_DIRPATH_INPUT_TEXT        0x01
#define OCI_DIRPATH_INPUT_UNKNOWN     0x08
#define OCI_DIRPATH_STREAM_VERSION_1        100
#define OCI_DIRPATH_STREAM_VERSION_2        200
#define OCI_DIRPATH_STREAM_VERSION_3        300
#define OCI_DT_DAY_BELOW_VALID     0x2
#define OCI_DT_DAY_MISSING_FROM_1582 0x1000
#define OCI_DT_HOUR_BELOW_VALID    0x80
#define OCI_DT_INVALID_DAY         0x1
#define OCI_DT_INVALID_FORMAT      0x8000
#define OCI_DT_INVALID_HOUR        0x40
#define OCI_DT_INVALID_MINUTE      0x100
#define OCI_DT_INVALID_MONTH       0x4
#define OCI_DT_INVALID_SECOND      0x400
#define OCI_DT_INVALID_TIMEZONE    0x4000
#define OCI_DT_INVALID_YEAR        0x10
#define OCI_DT_MINUTE_BELOW_VALID  0x200
#define OCI_DT_MONTH_BELOW_VALID   0x8
#define OCI_DT_SECOND_BELOW_VALID  0x800
#define OCI_DT_YEAR_BELOW_VALID    0x20
#define OCI_DT_YEAR_ZERO           0x2000
#define OCI_DTYPE_AQAGENT 60
#define OCI_DTYPE_AQDEQ_OPTIONS 58
#define OCI_DTYPE_AQENQ_OPTIONS 57
#define OCI_DTYPE_AQLIS_MSG_PROPERTIES 76
#define OCI_DTYPE_DATETIME 62
#define OCI_DTYPE_AQLIS_OPTIONS 75
#define OCI_DTYPE_AQMSG_PROPERTIES 59
#define OCI_DTYPE_AQNFY_DESCRIPTOR  64
#define OCI_DTYPE_CHDES         77
#define OCI_DTYPE_COMPLEXOBJECTCOMP  55
#define OCI_DTYPE_CQDES  80
#define OCI_DTYPE_DATE 65
#define OCI_DTYPE_FILE 56
#define OCI_DTYPE_FIRST 50
#define OCI_DTYPE_INTERVAL_DS 63
#define OCI_DTYPE_INTERVAL_YM 62
#define OCI_DTYPE_LAST          81
#define OCI_DTYPE_LOB 50
#define OCI_DTYPE_LOB_REGION    81
#define OCI_DTYPE_LOCATOR 61
#define OCI_DTYPE_PARAM 53
#define OCI_DTYPE_RESERVED_1    74
#define OCI_DTYPE_ROW_CHDES     79
#define OCI_DTYPE_ROWID  54
#define OCI_DTYPE_RSET 52
#define OCI_DTYPE_SIGNATURE     73
#define OCI_DTYPE_SNAP 51
#define OCI_DTYPE_SRVDN         72
#define OCI_DTYPE_TABLE_CHDES   78
#define OCI_DTYPE_TIME 66
#define OCI_DTYPE_TIME_TZ 67
#define OCI_DTYPE_TIMESTAMP 68
#define OCI_DTYPE_TIMESTAMP_LTZ 70
#define OCI_DTYPE_TIMESTAMP_TZ 69
#define OCI_DTYPE_UCB           71
#define OCI_DUMP_HEAP       0x80
#define OCI_DYNAMIC_FETCH     0x00000002
#define OCI_ENABLE_NLS_VALIDATION     0x01000000
#define OCI_ENQ_BEFORE          2
#define OCI_ENQ_IMMEDIATE       1
#define OCI_ENQ_ON_COMMIT       2
#define OCI_ENQ_TOP             3
#define OCI_ENV_NO_MUTEX 0x08
#define OCI_ENV_NO_UCB 0x01
#define OCI_ENVCR_RESERVED3 0x00010000
OCI_ERROR = -1
#define OCI_ERROR_MAXMSG_SIZE   1024
#define OCI_EVENT_DEREG 0x5
#define OCI_EVENT_DROP_DB 0x4
#define OCI_EVENT_NONE 0x0
#define OCI_EVENT_OBJCHANGE 0x6
#define OCI_EVENT_QUERYCHANGE 0x7
#define OCI_EVENT_SHUTDOWN 0x2
#define OCI_EVENT_SHUTDOWN_ANY 0x3
#define OCI_EVENT_STARTUP 0x1
#define OCI_EVENTS          0x00000004
#define OCI_EVENTTYPE_HA            0
#define OCI_EXACT_FETCH            0x00000002
#define OCI_EXACT_FETCH_RESERVED_1 0x00000200
#define OCI_EXEC_RESERVED_2        0x00000800
#define OCI_EXEC_RESERVED_3        0x00002000
#define OCI_EXEC_RESERVED_4        0x00004000
#define OCI_EXEC_RESERVED_5        0x00008000
#define OCI_EXEC_RESERVED_6        0x00010000
#define OCI_FASTPATH         0x0010
#define OCI_FETCH_ABSOLUTE   0x00000020
#define OCI_FETCH_CURRENT    0x00000001
#define OCI_FETCH_FIRST      0x00000004
#define OCI_FETCH_LAST       0x00000008
#define OCI_FETCH_NEXT       0x00000002
#define OCI_FETCH_PRIOR      0x00000010
#define OCI_FETCH_RELATIVE   0x00000040
#define OCI_FETCH_RESERVED_1 0x00000080
#define OCI_FETCH_RESERVED_2 0x00000100
#define OCI_FETCH_RESERVED_3 0x00000200
#define OCI_FETCH_RESERVED_4 0x00000400
#define OCI_FETCH_RESERVED_5 0x00000800
#define OCI_FLOW_CONTROL_NO_TIMEOUT      -1
#define OCI_FNCODE_APPCTXCLEARALL   137
#define OCI_FNCODE_APPCTXSET        136
#define OCI_FNCODE_AQDEQ  91
#define OCI_FNCODE_AQDEQARRAY  111
#define OCI_FNCODE_AQENQ  90
#define OCI_FNCODE_AQENQARRAY  110
#define OCI_FNCODE_AQENQSTREAM        124
#define OCI_FNCODE_AQGETREPLAY        125
#define OCI_FNCODE_AQLISTEN  96
#define OCI_FNCODE_AQRESETREPLAY      126
#define OCI_FNCODE_ARRAYDESCRIPTORALLOC 127
#define OCI_FNCODE_ARRAYDESCRIPTORFREE  128
#define OCI_FNCODE_ATTRGET 54
#define OCI_FNCODE_ATTRSET 55
#define OCI_FNCODE_BINDARRAYOFSTRUCT   20
#define OCI_FNCODE_BINDBYNAME 67
#define OCI_FNCODE_BINDBYPOS 66
#define OCI_FNCODE_BINDDYNAMIC   17
#define OCI_FNCODE_BINDOBJECT  18
#define OCI_FNCODE_CPOOLCREATE  100
#define OCI_FNCODE_CPOOLDESTROY 101
#define OCI_FNCODE_DBSHUTDOWN 121
#define OCI_FNCODE_DBSTARTUP 120
#define OCI_FNCODE_DEFINEARRAYOFSTRUCT  27
#define OCI_FNCODE_DEFINEBYPOS 65
#define OCI_FNCODE_DEFINEDYNAMIC   26
#define OCI_FNCODE_DEFINEOBJECT  25
#define OCI_FNCODE_DESCRIBEANY  32
#define OCI_FNCODE_DESCRIPTORALLOC  4
#define OCI_FNCODE_DESCRIPTORFREE  5
#define OCI_FNCODE_ENVINIT   6
#define OCI_FNCODE_ERRORGET   37
#define OCI_FNCODE_HANDLEALLOC  2
#define OCI_FNCODE_HANDLEFREE  3
#define OCI_FNCODE_INITIALIZE     1
#define OCI_FNCODE_KERBATTRSET 52
#define OCI_FNCODE_LDATOSVCCTX 59
#define OCI_FNCODE_LOBAPPEND  43
#define OCI_FNCODE_LOBARRAYREAD       122
#define OCI_FNCODE_LOBARRAYWRITE      123
#define OCI_FNCODE_LOBASSIGN  68
#define OCI_FNCODE_LOBCHARSETFORM  73
#define OCI_FNCODE_LOBCHARSETID  72
#define OCI_FNCODE_LOBCLOSE  82
#define OCI_FNCODE_LOBCLOSEFILE  39
#define OCI_FNCODE_LOBCOPY  42
#define OCI_FNCODE_LOBCOPY2    112
#define OCI_FNCODE_LOBCREATETEMP  87
#define OCI_FNCODE_LOBDISABLEBUFFERING 78
#define OCI_FNCODE_LOBENABLEBUFFERING  71
#define OCI_FNCODE_LOBERASE  44
#define OCI_FNCODE_LOBERASE2   113
#define OCI_FNCODE_LOBFILECLOSEALL  86
#define OCI_FNCODE_LOBFILEEXISTS  85
#define OCI_FNCODE_LOBFILEGETNAME  75
#define OCI_FNCODE_LOBFILEISOPEN  84
#define OCI_FNCODE_LOBFILESETNAME  74
#define OCI_FNCODE_LOBFLUSHBUFFER 79
#define OCI_FNCODE_LOBFRAGDEL       132
#define OCI_FNCODE_LOBFRAGINS       131
#define OCI_FNCODE_LOBFRAGMOV       133
#define OCI_FNCODE_LOBFRAGREP       134
#define OCI_FNCODE_LOBFREETEMP  88
#define OCI_FNCODE_LOBGETDEDUPLICATEREGIONS 135
#define OCI_FNCODE_LOBGETOPT        129
#define OCI_FNCODE_LOBGETSTORAGELIMIT 119
#define OCI_FNCODE_LOBISEQUAL  69
#define OCI_FNCODE_LOBISINIT  70
#define OCI_FNCODE_LOBISOPEN  83
#define OCI_FNCODE_LOBISTEMP  89
#define OCI_FNCODE_LOBLENGTH  45
#define OCI_FNCODE_LOBLENGTH2  114
#define OCI_FNCODE_LOBLOADFROMFILE 80
#define OCI_FNCODE_LOBLOADFROMFILE2  115
#define OCI_FNCODE_LOBLOCATORASSIGN 94
#define OCI_FNCODE_LOBOPEN  81
#define OCI_FNCODE_LOBOPENFILE  38
#define OCI_FNCODE_LOBREAD  47
#define OCI_FNCODE_LOBREAD2    116
#define OCI_FNCODE_LOBSETOPT        130
#define OCI_FNCODE_LOBTRIM  46
#define OCI_FNCODE_LOBTRIM2    117
#define OCI_FNCODE_LOBWRITE  48
#define OCI_FNCODE_LOBWRITE2   118
#define OCI_FNCODE_LOGOFF 77
#define OCI_FNCODE_LOGON 76
#define OCI_FNCODE_LOGON2 102
#define OCI_FNCODE_MAXFCN             137
#define OCI_FNCODE_PARAMGET 57
#define OCI_FNCODE_PARAMSET 56
#define OCI_FNCODE_PASSWORDCHANGE   12
#define OCI_FNCODE_RESET  92
#define OCI_FNCODE_ROWIDTOCHAR  103
#define OCI_FNCODE_SERVERATTACH   7
#define OCI_FNCODE_SERVERDETACH   8
#define OCI_FNCODE_SERVERVERSION  51
#define OCI_FNCODE_SESSIONBEGIN  10
#define OCI_FNCODE_SESSIONEND   11
#define OCI_FNCODE_SESSIONGET   106
#define OCI_FNCODE_SESSIONRELEASE 107
#define OCI_FNCODE_SPOOLCREATE  104
#define OCI_FNCODE_SPOOLDESTROY 105
#define OCI_FNCODE_STMTEXECUTE  21
#define OCI_FNCODE_STMTFETCH   28
#define OCI_FNCODE_STMTGETBIND   29
#define OCI_FNCODE_STMTGETPIECEINFO   58
#define OCI_FNCODE_STMTPREPARE   13
#define OCI_FNCODE_STMTPREPARE2 108
#define OCI_FNCODE_STMTRELEASE 109
#define OCI_FNCODE_STMTSETPIECEINFO   61
#define OCI_FNCODE_SVC2HST 97
#define OCI_FNCODE_SVCCTXBREAK 50
#define OCI_FNCODE_SVCCTXTOLDA  93
#define OCI_FNCODE_SVCRH   98
#define OCI_FNCODE_TRANSCOMMIT  35
#define OCI_FNCODE_TRANSDETACH  34
#define OCI_FNCODE_TRANSFORGET 62
#define OCI_FNCODE_TRANSMULTIPREPARE   99
#define OCI_FNCODE_TRANSPREPARE 63
#define OCI_FNCODE_TRANSROLLBACK  64
#define OCI_FNCODE_TRANSSTART  33
#define OCI_FNCODE_UBINDBYNAME 95
#define OCI_FO_ABORT        0x00000002
#define OCI_FO_BEGIN        0x00000008
#define OCI_FO_END          0x00000001
#define OCI_FO_ERROR        0x00000010
#define OCI_FO_NONE           0x00000001
#define OCI_FO_REAUTH       0x00000004
#define OCI_FO_RETRY        25410
#define OCI_FO_SELECT         0x00000004
#define OCI_FO_SESSION        0x00000002
#define OCI_FO_TXNAL          0x00000008
#define OCI_HA_SOURCE_ASM_INSTANCE        5
#define OCI_HA_SOURCE_DATABASE            1
#define OCI_HA_SOURCE_INSTANCE            0
#define OCI_HA_SOURCE_NODE                2
#define OCI_HA_SOURCE_SERVICE             3
#define OCI_HA_SOURCE_SERVICE_MEMBER      4
#define OCI_HA_SOURCE_SERVICE_PRECONNECT  6
#define OCI_HA_STATUS_DOWN          0
#define OCI_HA_STATUS_UP            1
#define OCI_HTYPE_ADMIN         28
#define OCI_HTYPE_AUTHINFO      OCI_HTYPE_SESSION
#define OCI_HTYPE_BIND           5
#define OCI_HTYPE_COMPLEXOBJECT 11
#define OCI_HTYPE_CPOOL         26
#define OCI_HTYPE_DEFINE         6
#define OCI_HTYPE_DESCRIBE       7
#define OCI_HTYPE_DIRPATH_COLUMN_ARRAY 15
#define OCI_HTYPE_DIRPATH_CTX   14
#define OCI_HTYPE_DIRPATH_FN_COL_ARRAY 19
#define OCI_HTYPE_DIRPATH_FN_CTX       18
#define OCI_HTYPE_DIRPATH_STREAM       16
OCI_HTYPE_ENV            =1
OCI_HTYPE_ERROR          =2
OCI_HTYPE_EVENT          =29
OCI_HTYPE_FIRST          =1
OCI_HTYPE_LAST           =29
OCI_HTYPE_PROC           =17
OCI_HTYPE_SECURITY       =12
OCI_HTYPE_SERVER         =8
OCI_HTYPE_SESSION        =9
OCI_HTYPE_SPOOL         =27
OCI_HTYPE_STMT          = 4
OCI_HTYPE_SUBSCRIPTION  = 13
OCI_HTYPE_SVCCTX        = 3
OCI_HTYPE_TRANS         =10
OCI_HTYPE_XADFIELD      =22
OCI_HTYPE_XADGRANULE    =23
OCI_HTYPE_XADIO         =25
OCI_HTYPE_XADRECORD     =24
OCI_HTYPE_XADSESSION    =20
OCI_HTYPE_XADTABLE      =21
OCI_INSTANCE_TYPE_OSM      =2
OCI_INSTANCE_TYPE_RDBMS    =1
OCI_INSTANCE_TYPE_UNKNOWN  =0
OCI_INTER_DAY_BELOW_VALID     =0x2
OCI_INTER_FRACSEC_BELOW_VALID =0x2000
OCI_INTER_HOUR_BELOW_VALID    =0x80
OCI_INTER_INVALID_DAY         =0x1
OCI_INTER_INVALID_FRACSEC     =0x1000
OCI_INTER_INVALID_HOUR        =0x40
OCI_INTER_INVALID_MINUTE      =0x100
OCI_INTER_INVALID_MONTH       =0x4
OCI_INTER_INVALID_SECOND      =0x400
OCI_INTER_INVALID_YEAR        =0x10
OCI_INTER_MINUTE_BELOW_VALID  =0x200
OCI_INTER_MONTH_BELOW_VALID   =0x8
OCI_INTER_SECOND_BELOW_VALID  =0x800
OCI_INTER_YEAR_BELOW_VALID    =0x20
OCI_INVALID_HANDLE =-2
OCI_IOV            =   0x00000200
#OCI_LOBMAXSIZE     =   MINUB4MAXVAL
OCI_LOCK_DELAYED    = 1
OCI_LOCK_IMMEDIATE  = 0
OCI_LOGON2_CPOOL    =   OCI_CPOOL
OCI_LOGON2_PROXY    =   0x0008
OCI_LOGON2_SPOOL    =   0x0001
OCI_LOGON2_STMTCACHE=   0x0004
OCI_MAX_FNS   =100
OCI_MEM_CLN   =      0x02
OCI_MEM_FLUSH =      0x04
OCI_MEM_INIT  =      0x01
OCI_MIGRATE   =      0x00000001
OCI_MSG_BUFFERED        =2
OCI_MSG_EXPIRED         =3
OCI_MSG_NO_DELAY        =0
OCI_MSG_NO_EXPIRATION   =-1
OCI_MSG_PERSISTENT      =         1
OCI_MSG_PERSISTENT_OR_BUFFERED   = 3
OCI_MSG_PROCESSED       =2
OCI_MSG_READY           =0
OCI_MSG_WAITING         =1
OCI_MUTEX_ENV_ONLY      =0x00080000
OCI_MUTEX_TRY                 =0x00200000
OCI_NCHAR_LITERAL_REPLACE_OFF =0x00800000
OCI_NCHAR_LITERAL_REPLACE_ON  =0x00400000
OCI_NEED_DATA =99
OCI_NEW_LENGTH_SEMANTICS  =0x00020000
OCI_NO_AC_DDL =1
OCI_NO_DATA =100
OCI_NO_MUTEX          =0x00000080
OCI_NO_MUTEX_STMT     =0x00040000
OCI_NO_RESULT_CACHE   =0x00040000
OCI_NO_SHARING        =0x01
OCI_NO_UCB            =0x00000040
OCI_NON_BLOCKING           =0x00000040
OCI_NTFN_GROUPING_FOREVER  =-1
OCI_NTV_SYNTAX  = 1
OCI_NW_SUPPORTED   =0
OCI_NW_UNSUPPORTED =1
OCI_OBJECT          = 0x00000002
#define OCI_OPCODE_ALLOPS 0x0
#define OCI_OPCODE_ALLROWS 0x1
#define OCI_OPCODE_ALTER 0x10
#define OCI_OPCODE_DELETE 0x8
#define OCI_OPCODE_DROP 0x20
#define OCI_OPCODE_INSERT 0x2
#define OCI_OPCODE_UNKNOWN 0x40
#define OCI_OPCODE_UPDATE 0x4
#define OCI_OTYPE_FUNC          5
#define OCI_OTYPE_NAME 1
#define OCI_OTYPE_PKG           6
#define OCI_OTYPE_PROC          4
#define OCI_OTYPE_PTR  3
#define OCI_OTYPE_REF  2
#define OCI_OTYPE_STMT          7
#define OCI_OTYPE_SYN           3
#define OCI_OTYPE_TABLE         1
#define OCI_OTYPE_UNK           0
#define OCI_OTYPE_VIEW          2
#define OCI_PARAM_IN 0x01
#define OCI_PARAM_OUT 0x02
#define OCI_PARSE_ONLY             0x00000100
#define OCI_PIECEWISE         0x00000004
#define OCI_PRELIM_AUTH     0x00000008
#define OCI_PREP_AFC_PAD_OFF  0x08
#define OCI_PREP_AFC_PAD_ON   0x04
#define OCI_PREP_RESERVED_1   0x02
#define OCI_PREP2_CACHE_SEARCHONLY    0x0010
#define OCI_PREP2_GET_PLSQL_WARNINGS  0x0020
#define OCI_PREP2_RESERVED_1          0x0040
#define OCI_REG_LDAPONLY    0x00002000
#define OCI_RESERVED_FOR_INT_USE 200
#define OCI_RESERVED1       0x00000008
#define OCI_RESERVED2       0x00000020
#define OCI_RESULT_CACHE           0x00020000
#define OCI_ROWCBK_DONE   -24201
#define OCI_ROWID_LEN             23
#define OCI_SB2_IND_PTR       0x00000001
#define OCI_SERVER_NORMAL               0x1
#define OCI_SERVER_NOT_CONNECTED        0x0
#define OCI_SERVER_STATS    0x20
#define OCI_SESSEND_RESERVED_1 0x0001
#define OCI_SESSEND_RESERVED_2 0x0002
#define OCI_SESSGET_CPOOL      OCI_CPOOL
#define OCI_SESSGET_CREDEXT    0x0010
#define OCI_SESSGET_CREDPROXY  0x0008
#define OCI_SESSGET_PURITY_NEW     0x0040
#define OCI_SESSGET_PURITY_SELF    0x0080
#define OCI_SESSGET_SPOOL      0x0001
#define OCI_SESSGET_SPOOL_MATCHANY 0x0020
#define OCI_SESSGET_STMTCACHE  0x0004
#define OCI_SESSION_STATEFUL   2
#define OCI_SESSION_STATELESS  1
#define OCI_SESSION_STATELESS_APP  3
#define OCI_SESSION_STATELESS_CAL  1
#define OCI_SESSION_STATELESS_DEF  0
#define OCI_SESSION_STATELESS_TXN  2
#define OCI_SESSRLS_DROPSESS 0x0001
#define OCI_SESSRLS_RETAG    0x0002
#define OCI_SHARED          0x00000010
#define OCI_SHARED_EXT      0x00000100
#define OCI_SHOW_DML_WARNINGS      0x00000400
#define OCI_SP_SUPPORTED   0
#define OCI_SP_UNSUPPORTED 1
#define OCI_SPC_HOMOGENEOUS  0x0002
#define OCI_SPC_NO_RLB       0x0008
#define OCI_SPC_REINITIALIZE 0x0001
#define OCI_SPC_STMTCACHE    0x0004
#define OCI_SPD_FORCE        0x0001
#define OCI_SPOOL_ATTRVAL_FORCEGET 2
#define OCI_SPOOL_ATTRVAL_NOWAIT   1
#define OCI_SPOOL_ATTRVAL_WAIT     0
#define OCI_SQLSTATE_SIZE 5
#define OCI_SRVATCH_RESERVED5 0x01000000
#define OCI_SRVATCH_RESERVED6 0x02000000
#define OCI_STATELESS_APP   0x00000200
#define OCI_STATELESS_CALL  0x00000080
#define OCI_STATELESS_TXN   0x00000100
#define OCI_STILL_EXECUTING -3123
#define OCI_STM_RESERVED4   0x00100000
#define OCI_STMT_CACHE      0x00000040
#define OCI_STMT_SCROLLABLE_READONLY 0x00000008
#define OCI_STMT_STATE_END_OF_FETCH 0x0003
#define OCI_STMT_STATE_EXECUTED     0x0002
#define OCI_STMT_STATE_INITIALIZED  0x0001
#define OCI_STRLS_CACHE_DELETE      0x0010
#define OCI_SUBSCR_CQ_QOS_BEST_EFFORT 0x02
#define OCI_SUBSCR_CQ_QOS_CLQRYCACHE 0x04
#define OCI_SUBSCR_CQ_QOS_QUERY  0x01
#define OCI_SUBSCR_NAMESPACE_ANONYMOUS   0
#define OCI_SUBSCR_NAMESPACE_AQ          1
#define OCI_SUBSCR_NAMESPACE_DBCHANGE    2
#define OCI_SUBSCR_NAMESPACE_MAX         3
#define OCI_SUBSCR_NTFN_GROUPING_CLASS_TIME 1
#define OCI_SUBSCR_NTFN_GROUPING_TYPE_LAST    2
#define OCI_SUBSCR_NTFN_GROUPING_TYPE_SUMMARY 1
#define OCI_SUBSCR_PRES_DEFAULT             0
#define OCI_SUBSCR_PRES_MAX                 2
#define OCI_SUBSCR_PRES_XML                 1
#define OCI_SUBSCR_PROTO_HTTP               3
#define OCI_SUBSCR_PROTO_MAIL               1
#define OCI_SUBSCR_PROTO_MAX                4
#define OCI_SUBSCR_PROTO_OCI                0
#define OCI_SUBSCR_PROTO_SERVER             2
#define OCI_SUBSCR_QOS_MULTICBK             0x20
#define OCI_SUBSCR_QOS_PAYLOAD              0x02
#define OCI_SUBSCR_QOS_PURGE_ON_NTFN        0x10
#define OCI_SUBSCR_QOS_RELIABLE             0x01
#define OCI_SUBSCR_QOS_REPLICATE            0x04
#define OCI_SUBSCR_QOS_SECURE               0x08
OCI_SUCCESS  = 0
#define OCI_SUCCESS_WITH_INFO 1
#define OCI_SUPPRESS_NLS_VALIDATION   0x00100000
#define OCI_SYSASM          0x00008000
#define OCI_SYSDBA          0x00000002
#define OCI_SYSOPER         0x00000004
#define OCI_TEMP_BLOB 1
#define OCI_TEMP_CLOB 2
#define OCI_TEMP_NCLOB 3
#define OCI_THREADED        0x00000001
#define OCI_TRANS_ISOLMASK     0x0000ff00
#define OCI_TRANS_JOIN         0x00000002
#define OCI_TRANS_LOOSE        0x00010000
#define OCI_TRANS_NEW          0x00000001
#define OCI_TRANS_NOMIGRATE    0x00100000
#define OCI_TRANS_OTHRMASK     0xfff00000
#define OCI_TRANS_OTSRESUME    0x00400000
#define OCI_TRANS_PROMOTE      0x00000008
#define OCI_TRANS_READONLY     0x00000100
#define OCI_TRANS_READWRITE    0x00000200
#define OCI_TRANS_RESUME       0x00000004
#define OCI_TRANS_SEPARABLE    0x00200000
#define OCI_TRANS_SERIALIZABLE 0x00000400
#define OCI_TRANS_STARTMASK    0x000000ff
#define OCI_TRANS_TIGHT        0x00020000
#define OCI_TRANS_TWOPHASE      0x01000000
#define OCI_TRANS_TYPEMASK     0x000f0000
#define OCI_TRANS_WRITEBATCH    0x00000001
#define OCI_TRANS_WRITEIMMED    0x00000002
#define OCI_TRANS_WRITENOWAIT   0x00000008
#define OCI_TRANS_WRITEWAIT     0x00000004
#define OCI_UCS2ID            1000
#define OCI_USE_LDAP        0x00001000
#define OCI_UTF16           0x00004000
#define OCI_UTF16ID           1000
#define OCI_V7_SYNTAX 2
#define OCI_V8_SYNTAX 3
#define OCIP_ATTR_DIRPATH_VARRAY_INDEX      213
#define OCIP_ICACHE         0x00000010
#define   OCI_FILE_BIN      0
#define   OCI_FILE_STDERR   4
#define   OCI_FILE_STDIN    2
#define   OCI_FILE_STDOUT   3
#define   OCI_FILE_TEXT     1
#define  OCI_DURATION_BEGIN (OCIDuration)10
#define  OCI_DURATION_CALLOUT (OCIDuration)(OCI_DURATION_BEGIN+4)
#define  OCI_DURATION_DEFAULT (OCIDuration)(OCI_DURATION_BEGIN-2)
#define  OCI_DURATION_INVALID 0xFFFF
#define  OCI_DURATION_LAST OCI_DURATION_CALLOUT
#define  OCI_DURATION_NEXT (OCIDuration)(OCI_DURATION_BEGIN-4)
#define  OCI_DURATION_NULL (OCIDuration)(OCI_DURATION_BEGIN-1)
#define  OCI_DURATION_PROCESS (OCIDuration)(OCI_DURATION_BEGIN-5)
#define  OCI_DURATION_SESSION (OCIDuration)(OCI_DURATION_BEGIN)
#define  OCI_DURATION_STATEMENT (OCIDuration)(OCI_DURATION_BEGIN+3)
#define  OCI_DURATION_TRANS (OCIDuration)(OCI_DURATION_BEGIN+1)
#define  OCI_DURATION_USER_CALLBACK (OCIDuration)(OCI_DURATION_BEGIN-3)
#define  OCI_DURATION_CALL (OCIDuration)(OCI_DURATION_BEGIN+2)
#define  OCI_STMT_ALTER   7
#define  OCI_STMT_BEGIN   8
#define  OCI_STMT_CALL    10
#define  OCI_STMT_CREATE  5
#define  OCI_STMT_DECLARE 9
#define  OCI_STMT_DELETE  3
#define  OCI_STMT_DROP    6
#define  OCI_STMT_INSERT  4
#define  OCI_STMT_SELECT  1
#define  OCI_STMT_UNKNOWN 0
#define  OCI_STMT_UPDATE  2
#define OCI_ADJUST_UNK            10
#define OCI_ANSI_DATE             1
#define OCI_ATTR_CACHE_ARRAYFLUSH 0x00000040
#define OCI_ATTR_OBJECT_DETECTCHANGE            0x00000020
#define OCI_ATTR_OBJECT_NEWNOTNULL   0x00000010
#define OCI_COHERENCY_ALWAYS (OCIRefreshOpt)5
#define OCI_COHERENCY_NONE   (OCIRefreshOpt)2
#define OCI_COHERENCY_NULL   (OCIRefreshOpt)4
#define OCI_DATE_DAY_BELOW_VALID        0x2
#define OCI_DATE_DAY_MISSING_FROM_1582  0x1000
#define OCI_DATE_HOUR_BELOW_VALID       0x80
#define OCI_DATE_INVALID_DAY            0x1
#define OCI_DATE_INVALID_FORMAT         0x8000
#define OCI_DATE_INVALID_HOUR           0x40
#define OCI_DATE_INVALID_MINUTE         0x100
#define OCI_DATE_INVALID_MONTH          0x4
#define OCI_DATE_INVALID_SECOND         0x400
#define OCI_DATE_INVALID_YEAR           0x10
#define OCI_DATE_MINUTE_BELOW_VALID     0x200
#define OCI_DATE_MONTH_BELOW_VALID      0x8
#define OCI_DATE_SECOND_BELOW_VALID     0x800
#define OCI_DATE_YEAR_BELOW_VALID       0x20
#define OCI_DATE_YEAR_ZERO              0x2000
#define OCIDateGetTime(/*IN*/date, /*OUT*/hour, /*OUT*/min, /*OUT*/sec) /* LOGIC REMOVED BY IAN HAY */
#define OCIDateGetDate(/*IN*/date, /*OUT*/year, /*OUT*/month, /*OUT*/day) /* LOGIC REMOVED BY IAN HAY */
#define OCIDateSetTime(/*OUT*/date, /*IN*/hour, /*IN*/min, /*IN*/sec) /* LOGIC REMOVED BY IAN HAY */
#define OCIDateSetDate(date, year, month, day) /* LOGIC REMOVED BY IAN HAY */

#define OCI_DBSHUTDOWN_ABORT              4
#define OCI_DBSHUTDOWN_FINAL              5
#define OCI_DBSHUTDOWN_IMMEDIATE           3
#define OCI_DBSHUTDOWN_TRANSACTIONAL      1
#define OCI_DBSHUTDOWN_TRANSACTIONAL_LOCAL 2
#define OCI_DBSTARTUPFLAG_FORCE 0x00000001
#define OCI_DBSTARTUPFLAG_RESTRICT 0x00000002
#define OCI_EXTRACT_APPEND_VALUES      0x4
#define OCI_EXTRACT_CASE_SENSITIVE     0x1
#define OCI_EXTRACT_MULTIPLE           0x8
#define OCI_EXTRACT_TYPE_BOOLEAN         1
#define OCI_EXTRACT_TYPE_INTEGER         3
#define OCI_EXTRACT_TYPE_OCINUM          4
#define OCI_EXTRACT_TYPE_STRING          2
#define OCI_EXTRACT_UNIQUE_ABBREVS     0x2
#define OCI_FILE_APPEND            8
#define OCI_FILE_BACKWARD    2
#define OCI_FILE_CREATE            1
#define OCI_FILE_EXCL              2
#define OCI_FILE_EXIST             0
#define OCI_FILE_FORWARD     1
#define OCI_FILE_READ_ONLY         1
#define OCI_FILE_READ_WRITE        3
#define OCI_FILE_READONLY 1
#define OCI_FILE_SEEK_BEGINNING    1
#define OCI_FILE_SEEK_CURRENT      2
#define OCI_FILE_SEEK_END          3
#define OCI_FILE_TRUNCATE          4
#define OCI_FILE_WRITE_ONLY        2
#define OCI_IND_BADNULL (OCIInd)(-2)
#define OCI_IND_NOTNULL (OCIInd)0
#define OCI_IND_NOTNULLABLE (OCIInd)(-3)
#define OCI_IND_NULL (OCIInd)(-1)
#define OCI_INTHR_UNK 24
#define OCI_KERBCRED_CLIENT_IDENTIFIER   2
#define OCI_KERBCRED_PROXY               1
#define OCI_LOB_APPENDONLY    4
#define OCI_LOB_BUFFER_FREE   1
#define OCI_LOB_BUFFER_NOFREE 2
#define OCI_LOB_COMPRESS_OFF  0
#define OCI_LOB_COMPRESS_ON   1
#define OCI_LOB_DEDUPLICATE_OFF 0
#define OCI_LOB_DEDUPLICATE_ON  4
#define OCI_LOB_ENCRYPT_OFF   0
#define OCI_LOB_ENCRYPT_ON    2
#define OCI_LOB_FULLOVERWRITE 5
#define OCI_LOB_FULLREAD      6
#define OCI_LOB_OPT_ALLOCSIZE 8
#define OCI_LOB_OPT_COMPRESS  1
#define OCI_LOB_OPT_DEDUPLICATE 4
#define OCI_LOB_OPT_ENCRYPT   2
#define OCI_LOB_OPT_MIMETYPE 16
#define OCI_LOB_OPT_MODTIME  32
#define OCI_LOB_READONLY 1
#define OCI_LOB_READWRITE 2
#define OCI_LOB_WRITEONLY     3
#define OCI_LTYPE_ARG_FUNC      3
#define OCI_LTYPE_ARG_PROC      2
#define OCI_LTYPE_COLUMN        1
#define OCI_LTYPE_DB_SCH        10
#define OCI_LTYPE_NAME_VALUE    14
#define OCI_LTYPE_SCH_OBJ       9
#define OCI_LTYPE_SUBPRG        4
#define OCI_LTYPE_TABLE_ALIAS   12
#define OCI_LTYPE_TYPE_ARG_FUNC 8
#define OCI_LTYPE_TYPE_ARG_PROC 7
#define OCI_LTYPE_TYPE_ATTR     5
#define OCI_LTYPE_TYPE_METHOD   6
#define OCI_LTYPE_TYPE_SUBTYPE  11
#define OCI_LTYPE_UNK           0
#define OCI_LTYPE_VARIABLE_TYPE 13
#define OCI_MAJOR_VERSION  11
#define OCI_MEMORY_CLEARED  1
#define OCI_METHOD_IS_ABSTRACT(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_METHOD_IS_CONSTANT(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_METHOD_IS_CONSTRUCTOR(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_METHOD_IS_DESTRUCTOR(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_METHOD_IS_INLINE(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_METHOD_IS_MAP(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_METHOD_IS_OPERATOR(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_METHOD_IS_ORDER(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_METHOD_IS_OVERRIDING(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_METHOD_IS_PIPELINED(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_METHOD_IS_RNDS(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_METHOD_IS_RNPS(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_METHOD_IS_SELFISH(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_METHOD_IS_VIRTUAL(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_METHOD_IS_WNDS(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_METHOD_IS_WNPS(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_MINOR_VERSION  1
#define OCI_NLS_ABDAYNAME1    8
#define OCI_NLS_ABDAYNAME2    9
#define OCI_NLS_ABDAYNAME3    10
#define OCI_NLS_ABDAYNAME4    11
#define OCI_NLS_ABDAYNAME5    12
#define OCI_NLS_ABDAYNAME6    13
#define OCI_NLS_ABDAYNAME7    14
#define OCI_NLS_ABLANGUAGE    53
#define OCI_NLS_ABMONTHNAME1  27
#define OCI_NLS_ABMONTHNAME10 36
#define OCI_NLS_ABMONTHNAME11 37
#define OCI_NLS_ABMONTHNAME12 38
#define OCI_NLS_ABMONTHNAME2  28
#define OCI_NLS_ABMONTHNAME3  29
#define OCI_NLS_ABMONTHNAME4  30
#define OCI_NLS_ABMONTHNAME5  31
#define OCI_NLS_ABMONTHNAME6  32
#define OCI_NLS_ABMONTHNAME7  33
#define OCI_NLS_ABMONTHNAME8  34
#define OCI_NLS_ABMONTHNAME9  35
#define OCI_NLS_ABTERRITORY   80
#define OCI_NLS_AD            43
#define OCI_NLS_AM            41
#define OCI_NLS_BC            44
#define OCI_NLS_BINARY            0x1
#define OCI_NLS_CALENDAR      57
#define OCI_NLS_CASE_INSENSITIVE  0x10
#define OCI_NLS_CHARACTER_SET 55
#define OCI_NLS_CHARSET_FIXEDWIDTH 92
#define OCI_NLS_CHARSET_ID    93
#define OCI_NLS_CHARSET_MAXBYTESZ 91
#define OCI_NLS_CREDIT        48
#define OCI_NLS_CS_IANA_TO_ORA   0
#define OCI_NLS_CS_ORA_TO_IANA   1
#define OCI_NLS_DATEFORMAT    49
#define OCI_NLS_DAYNAME1      1
#define OCI_NLS_DAYNAME2      2
#define OCI_NLS_DAYNAME3      3
#define OCI_NLS_DAYNAME4      4
#define OCI_NLS_DAYNAME5      5
#define OCI_NLS_DAYNAME6      6
#define OCI_NLS_DAYNAME7      7
#define OCI_NLS_DDATEFORMAT   81
#define OCI_NLS_DEBIT         47
#define OCI_NLS_DECIMAL       45
#define OCI_NLS_DTIMEFORMAT   82
#define OCI_NLS_DUAL_CURRENCY 78
#define OCI_NLS_GROUP         46
#define OCI_NLS_INT_CURRENCY  50
#define OCI_NLS_INT_CURRENCYSEP 90
#define OCI_NLS_LANG_ISO_TO_ORA  2
#define OCI_NLS_LANG_ORA_TO_ISO  3
#define OCI_NLS_LANGUAGE      52
#define OCI_NLS_LINGUISTIC        0x2
#define OCI_NLS_LINGUISTIC_NAME    56
#define OCI_NLS_LISTSEP       86
#define OCI_NLS_LOC_CURRENCY  51
#define OCI_NLS_LOCALE_A2_ISO_TO_ORA 8
#define OCI_NLS_LOCALE_A2_ORA_TO_ISO 9
#define OCI_NLS_LOWERCASE         0x40
#define OCI_NLS_MAXBUFSZ   100
#define OCI_NLS_MONDECIMAL    87
#define OCI_NLS_MONGROUP      88
#define OCI_NLS_MONGROUPING   89
#define OCI_NLS_MONTHNAME1    15
#define OCI_NLS_MONTHNAME10   24
#define OCI_NLS_MONTHNAME11   25
#define OCI_NLS_MONTHNAME12   26
#define OCI_NLS_MONTHNAME2    16
#define OCI_NLS_MONTHNAME3    17
#define OCI_NLS_MONTHNAME4    18
#define OCI_NLS_MONTHNAME5    19
#define OCI_NLS_MONTHNAME6    20
#define OCI_NLS_MONTHNAME7    21
#define OCI_NLS_MONTHNAME8    22
#define OCI_NLS_MONTHNAME9    23
#define OCI_NLS_NCHARSET_ID   94
#define OCI_NLS_NO            40
#define OCI_NLS_NUMGROUPING   85
#define OCI_NLS_PM            42
#define OCI_NLS_SFDATEFORMAT  83
#define OCI_NLS_SFTIMEFORMAT  84
#define OCI_NLS_TERR_ISO_TO_ORA  4
#define OCI_NLS_TERR_ISO3_TO_ORA 6
#define OCI_NLS_TERR_ORA_TO_ISO  5
#define OCI_NLS_TERR_ORA_TO_ISO3 7
#define OCI_NLS_TERRITORY     54
#define OCI_NLS_UPPERCASE         0x20
#define OCI_NLS_WRITINGDIR    79
#define OCI_NLS_YES           39
#define OCI_NUMBER_DEFAULTPREC ((ub1)0)
#define OCI_NUMBER_DEFAULTSCALE ((sb1)MAXSB1MINVAL)
#define OCI_NUMBER_SIZE 22
#define OCI_OBJECT_DELETED 0x0002
#define OCI_OBJECT_IS_DELETED(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_OBJECT_IS_DIRTY(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_OBJECT_IS_NEW(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_OBJECT_IS_UPDATED(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_OBJECT_NEW     0x0001
#define OCI_OBJECT_UPDATED 0x0004
#define OCI_OBJECTCOPY_NOREF (ub1)0x01
#define OCI_OBJECTFREE_FORCE      (ub2)0x0001
#define OCI_OBJECTFREE_HEADER     (ub2)0x0004
#define OCI_OBJECTFREE_NONULL     (ub2)0x0002
#define OCI_OBJECTPROP_ALLOC_DURATION 5
#define OCI_OBJECTPROP_LIFETIME 1
#define OCI_OBJECTPROP_LOCK 6
#define OCI_OBJECTPROP_MARKSTATUS 7
#define OCI_OBJECTPROP_pinDur 4
#define OCI_OBJECTPROP_SCHEMA 2
#define OCI_OBJECTPROP_TABLE 3
#define OCI_OBJECTPROP_VIEW 8
#define OCI_ORACLE_DATE           0
#define OCI_PTYPE_ARG                 10
#define OCI_PTYPE_COL                 9
#define OCI_PTYPE_DATABASE            18
#define OCI_PTYPE_EVALUATION_CONTEXT  21
#define OCI_PTYPE_FUNC                4
#define OCI_PTYPE_LIST                11
#define OCI_PTYPE_NAME_VALUE          24
#define OCI_PTYPE_PKG                 5
#define OCI_PTYPE_PROC                3
#define OCI_PTYPE_RULE                19
#define OCI_PTYPE_RULE_SET            20
#define OCI_PTYPE_SCHEMA              17
#define OCI_PTYPE_SEQ                 8
#define OCI_PTYPE_SYN                 7
#define OCI_PTYPE_TABLE               1
#define OCI_PTYPE_TABLE_ALIAS         22
#define OCI_PTYPE_TYPE                6
#define OCI_PTYPE_TYPE_ARG            15
#define OCI_PTYPE_TYPE_ATTR           12
#define OCI_PTYPE_TYPE_COLL           13
#define OCI_PTYPE_TYPE_METHOD         14
#define OCI_PTYPE_TYPE_RESULT         16
#define OCI_PTYPE_UNK                 0
#define OCI_PTYPE_VARIABLE_TYPE       23
#define OCI_PTYPE_VIEW                2
#define OCI_STRING_MAXLEN  4000
#define OCI_TYPECODE_BDOUBLE     SQLT_IBDOUBLE
#define OCI_TYPECODE_BFILE       SQLT_BFILE
#define OCI_TYPECODE_BFLOAT      SQLT_IBFLOAT
#define OCI_TYPECODE_BLOB        SQLT_BLOB
#define OCI_TYPECODE_CFILE       SQLT_CFILE
#define OCI_TYPECODE_CHAR        SQLT_AFC
#define OCI_TYPECODE_CLOB        SQLT_CLOB
#define OCI_TYPECODE_DATE        SQLT_DAT
#define OCI_TYPECODE_DECIMAL     SQLT_PDN
#define OCI_TYPECODE_DOUBLE      22
#define OCI_TYPECODE_ERRHP         283
#define OCI_TYPECODE_FLOAT       SQLT_FLT
#define OCI_TYPECODE_INTEGER     SQLT_INT
#define OCI_TYPECODE_INTERVAL_DS SQLT_INTERVAL_DS
#define OCI_TYPECODE_INTERVAL_YM SQLT_INTERVAL_YM
#define OCI_TYPECODE_MLSLABEL    SQLT_LAB
#define OCI_TYPECODE_NAMEDCOLLECTION  SQLT_NCO
#define OCI_TYPECODE_NCHAR       286
#define OCI_TYPECODE_NCLOB       288
#define OCI_TYPECODE_NONE          0
#define OCI_TYPECODE_NUMBER      SQLT_NUM
#define OCI_TYPECODE_NVARCHAR2   287
#define OCI_TYPECODE_OBJECT      SQLT_NTY
#define OCI_TYPECODE_OCTET       245
#define OCI_TYPECODE_OPAQUE       58
#define OCI_TYPECODE_OTMFIRST    228
#define OCI_TYPECODE_OTMLAST     320
#define OCI_TYPECODE_PLS_INTEGER   266
#define OCI_TYPECODE_PTR         32
#define OCI_TYPECODE_RAW         SQLT_LVB
#define OCI_TYPECODE_REAL        21
#define OCI_TYPECODE_REF         SQLT_REF
#define OCI_TYPECODE_SIGNED16    28
#define OCI_TYPECODE_SIGNED32    29
#define OCI_TYPECODE_SIGNED8     27
#define OCI_TYPECODE_SMALLINT    246
#define OCI_TYPECODE_SYSFIRST    228
#define OCI_TYPECODE_SYSLAST     235
#define OCI_TYPECODE_TABLE       248
#define OCI_TYPECODE_TIME        SQLT_TIME
#define OCI_TYPECODE_TIME_TZ     SQLT_TIME_TZ
#define OCI_TYPECODE_TIMESTAMP   SQLT_TIMESTAMP
#define OCI_TYPECODE_TIMESTAMP_LTZ  SQLT_TIMESTAMP_LTZ
#define OCI_TYPECODE_TIMESTAMP_TZ  SQLT_TIMESTAMP_TZ
#define OCI_TYPECODE_UNSIGNED16  25
#define OCI_TYPECODE_UNSIGNED32  26
#define OCI_TYPECODE_UNSIGNED8   SQLT_BIN
#define OCI_TYPECODE_UROWID      SQLT_RDD
#define OCI_TYPECODE_VARCHAR     SQLT_CHR
#define OCI_TYPECODE_VARCHAR2    SQLT_VCS
#define OCI_TYPECODE_VARRAY      247
#define OCI_TYPEELEM_IS_REF(elem_flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEELEM_REF        0x8000
#define OCI_TYPEMETHOD_CLEAR_CONSTANT(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_CLEAR_CONSTRUCTOR(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_CLEAR_DESTRUCTOR(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_CLEAR_INLINE(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_CLEAR_MAP(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_CLEAR_OPERATOR(flag)  /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_CLEAR_ORDER(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_CLEAR_RNDS(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_CLEAR_RNPS(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_CLEAR_SELFISH(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_CLEAR_VIRTUAL(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_CLEAR_WNDS(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_CLEAR_WNPS(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_IS_ABSTRACT(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_IS_CONSTANT(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_IS_CONSTRUCTOR(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_IS_DESTRUCTOR(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_IS_INLINE(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_IS_MAP(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_IS_OPERATOR(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_IS_ORDER(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_IS_OVERRIDING(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_IS_PIPELINED(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_IS_RNDS(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_IS_RNPS(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_IS_SELFISH(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_IS_VIRTUAL(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_IS_WNDS(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_IS_WNPS(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_SET_CONSTANT(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_SET_CONSTRUCTOR(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_SET_DESTRUCTOR(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_SET_INLINE(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_SET_MAP(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_SET_OPERATOR(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_SET_ORDER(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_SET_RNDS(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_SET_RNPS(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_SET_SELFISH(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_SET_VIRTUAL(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_SET_WNDS(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEMETHOD_SET_WNPS(flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEPARAM_IS_REQUIRED(param_flag) /* LOGIC REMOVED BY IAN HAY */
#define OCI_TYPEPARAM_REQUIRED  0x0800
#define OCI_UCBTYPE_ENTRY       1
#define OCI_UCBTYPE_EXIT        2
#define OCI_UCBTYPE_REPLACE     3
#define OCI_VARRAY_MAXSIZE 4000
#define OCI_XMLTYPE_CREATE_BLOB      3
#define OCI_XMLTYPE_CREATE_CLOB      2
#define OCI_XMLTYPE_CREATE_OCISTRING 1
#define OCICoherency OCIRefreshOpt
#define OCIEXTPROC_ERROR   1
#define OCIEXTPROC_SUCCESS 0
#define OCIExtProcAllocCallMemory(withContext, amount) /* LOGIC REMOVED BY IAN HAY */
#define OCIExtProcGetEnv(withContext, envh, svch, errh) /* LOGIC REMOVED BY IAN HAY */
#define OCIExtProcRaiseExcp(withContext, errnum) /* LOGIC REMOVED BY IAN HAY */
#define OCIExtProcRaiseExcpWithMsg(withContext, errnum, errmsg, msglen) /* LOGIC REMOVED BY IAN HAY */
#define OCIFormatChar(variable)     /* LOGIC REMOVED BY IAN HAY */
#define OCIFormatDouble(variable)   /* LOGIC REMOVED BY IAN HAY */
#define OCIFormatDP 6
#define OCIFormatDvoid(variable)    /* LOGIC REMOVED BY IAN HAY */
#define OCIFormatEb1(variable)      /* LOGIC REMOVED BY IAN HAY */
#define OCIFormatEb2(variable)      /* LOGIC REMOVED BY IAN HAY */
#define OCIFormatEb4(variable)      /* LOGIC REMOVED BY IAN HAY */
#define OCIFormatEnd                /* LOGIC REMOVED BY IAN HAY */
#define OCIFormatEword(variable)    /* LOGIC REMOVED BY IAN HAY */
#define OCIFormatSb1(variable)      /* LOGIC REMOVED BY IAN HAY */
#define OCIFormatSb2(variable)      /* LOGIC REMOVED BY IAN HAY */
#define OCIFormatSb4(variable)      /* LOGIC REMOVED BY IAN HAY */
#define OCIFormatSbig_ora(variable)/* LOGIC REMOVED BY IAN HAY */
#define OCIFormatSword(variable)    /* LOGIC REMOVED BY IAN HAY */
#define OCIFormatText(variable)     /* LOGIC REMOVED BY IAN HAY */
#define OCIFormatUb1(variable)      /* LOGIC REMOVED BY IAN HAY */
#define OCIFormatUb2(variable)      /* LOGIC REMOVED BY IAN HAY */
#define OCIFormatUb4(variable)      /* LOGIC REMOVED BY IAN HAY */
#define OCIFormatUbig_ora(variable) /* LOGIC REMOVED BY IAN HAY */
#define OCIFormatUword(variable)    /* LOGIC REMOVED BY IAN HAY */
#define OCIInitializeStatementHandle(wctx, cursorno,  svch, stmthp, errh) /* LOGIC REMOVED BY IAN HAY */
#define OCINumberToLnx(num) ((lnxnum_t *)num)

#define NZERROR_SSL_TO_ORACLE(ssl_error_) /* LOGIC REMOVED BY IAN HAY */

#define NZT_DEFAULT_WRL    ((text *)"default:")
#define NZT_ENTR_WRL       ((text *)"entr:")
#define NZT_FILE_WRL       ((text *)"file:")
#define NZT_MAX_MD5  16
#define NZT_MAX_SHA1 20
#define NZT_MCS_WRL        ((text *)"mcs:")
#define NZT_ORACLE_WRL      ((text *)"oracle:")
#define NZT_REGISTRY_WRL   ((text *)"reg:")
#define NZT_SQLNET_WRL     ((text *)"sqlnet:")
#define NZTTKPUSAGE_CERT_SIGN 16
#define NZTTKPUSAGE_CODE_SIGN 8
#define NZTTKPUSAGE_INVALID_USE 0xffff
#define NZTTKPUSAGE_NONE 0
#define NZTTKPUSAGE_SMIME_ENCR 2
#define NZTTKPUSAGE_SMIME_SIGN 4
#define NZTTKPUSAGE_SSL 1
#define NZTTKPUSAGE_SSL_CLIENT 32
#define NUM_OCIXMLDBPARAMS 2
#define OCI_DIRPATH_COL_COMPLETE 0
#define OCI_DIRPATH_COL_ERROR    3
#define OCI_DIRPATH_COL_NULL     1
#define OCI_DIRPATH_COL_PARTIAL  2
#define OCI_DIRPATH_CONVERT      3
#define OCI_DIRPATH_DATASAVE_FINISH   1
#define OCI_DIRPATH_DATASAVE_PARTIAL  2
#define OCI_DIRPATH_DATASAVE_SAVEONLY 0
#define OCI_DIRPATH_EXPR_OBJ_CONSTR  1
#define OCI_DIRPATH_EXPR_REF_TBLNAME 3
#define OCI_DIRPATH_EXPR_SQL         2
#define OCI_DIRPATH_INDEX_MAINT_DONT_SKIP_UNUSABLE  3
#define OCI_DIRPATH_INDEX_MAINT_SINGLE_ROW     1
#define OCI_DIRPATH_INDEX_MAINT_SKIP_ALL            4
#define OCI_DIRPATH_INDEX_MAINT_SKIP_UNUSABLE       2
#define OCI_DIRPATH_LOAD         1
#define OCI_DIRPATH_NORMAL       1
#define OCI_DIRPATH_NOT_PREPARED 3
#define OCI_DIRPATH_PARTIAL      2
#define OCI_DIRPATH_UNLOAD       2

#nm -gU /Users/mac/sqllib/lib64/libdb2ci.dylib >>lola1.txt
def db2_oci_func(oci):
    mylist = [
'CLI_iniReadLong',
'CLI_iniReadStr',
'CLI_utlTraceBeginOCI',
'CLI_utlTraceEnd',
'CLI_utlTraceInit',
'CLI_utlTraceInteger',
'CLI_utlTracePassword',
'CLI_utlTraceString',
'CLI_utlTraceValue',
'CLI_utlTraceWString',
'AttributeList',
'EnvList',
'HandleTypeList',
'LdaList',
'NumberList',
'OCIArrayDescriptorAlloc',
'OCIArrayDescriptorFree',
'OCIAttrGet',
'OCIAttrSet',
'OCIBindArrayOfStruct',
'OCIBindByName',
'OCIBindByPos',
'OCIBindDynamic',
'OCIBreak',
'OCIClientVersion',
'OCIConnectionPoolCreate',
'OCIConnectionPoolDestroy',
'OCIDateAddDays',
'OCIDateAddMonths',
'OCIDateAssign',
'OCIDateCheck',
'OCIDateCompare',
'OCIDateDaysBetween',
'OCIDateFromText',
'OCIDateLastDay',
'OCIDateNextDay',
'OCIDateSysDate',
'OCIDateTimeAssignNS',
'OCIDateTimeCheckNS',
'OCIDateTimeCompareNS',
'OCIDateTimeConstructNS',
'OCIDateTimeGetDateNS',
'OCIDateTimeGetTimeNS',
'OCIDateToText',
'OCIDefineArrayOfStruct',
'OCIDefineByPos',
'OCIDefineDynamic',
'OCIDescribeAny',
'OCIDescriptorAlloc',
'OCIDescriptorFree',
'OCIEnvCreate',
'OCIEnvInit',
'OCIErrorGet',
'OCIFileClose',
'OCIFileExists',
'OCIFileFlush',
'OCIFileGetLength',
'OCIFileInit',
'OCIFileOpen',
'OCIFileRead',
'OCIFileSeek',
'OCIFileTerm',
'OCIFileWrite',
'OCIHandleAlloc',
'OCIHandleFree',
'OCIInitialize',
'OCILdaToSvcCtx',
'OCILobAppend',
'OCILobAssign',
'OCILobClose',
'OCILobCopy',
'OCILobCreateTemporary',
'OCILobDisableBuffering',
'OCILobEnableBuffering',
'OCILobErase',
'OCILobFlushBuffer',
'OCILobFreeTemporary',
'OCILobGetLength',
'OCILobIsEqual',
'OCILobIsOpen',
'OCILobIsTemporary',
'OCILobLocatorAssign',
'OCILobLocatorIsInit',
'OCILobOpen',
'OCILobRead',
'OCILobTrim',
'OCILobWrite',
'OCILogoff',
'OCILogon',
'OCILogon2',
'OCINumberAbs',
'OCINumberAdd',
'OCINumberArcCos',
'OCINumberArcSin',
'OCINumberArcTan',
'OCINumberArcTan2',
'OCINumberAssign',
'OCINumberCeil',
'OCINumberCmp',
'OCINumberCos',
'OCINumberDec',
'OCINumberDiv',
'OCINumberExp',
'OCINumberFloor',
'OCINumberFromInt',
'OCINumberFromReal',
'OCINumberFromText',
'OCINumberHypCos',
'OCINumberHypSin',
'OCINumberHypTan',
'OCINumberInc',
'OCINumberIntPower',
'OCINumberIsInt',
'OCINumberIsZero',
'OCINumberLn',
'OCINumberLog',
'OCINumberMod',
'OCINumberMul',
'OCINumberNeg',
'OCINumberPower',
'OCINumberPrec',
'OCINumberRound',
'OCINumberSetPi',
'OCINumberSetZero',
'OCINumberShift',
'OCINumberSign',
'OCINumberSin',
'OCINumberSqrt',
'OCINumberSub',
'OCINumberTan',
'OCINumberToInt',
'OCINumberToReal',
'OCINumberToRealArray',
'OCINumberToText',
'OCINumberTrunc',
'OCIParamGet',
'OCIPasswordChange',
'OCIPing',
'OCIRawAllocSize',
'OCIRawAssignBytes',
'OCIRawAssignRaw',
'OCIRawPtr',
'OCIRawResize',
'OCIRawSize',
'OCIReset',
'OCIResultSetToStmt',
'OCIRowidToChar',
'OCIServerAttach',
'OCIServerDetach',
'OCIServerVersion',
'OCISessionBegin',
'OCISessionEnd',
'OCISessionGet',
'OCISessionPoolCreate',
'OCISessionPoolDestroy',
'OCISessionRelease',
'OCIStmtExecute',
'OCIStmtFetch',
'OCIStmtFetch2',
'OCIStmtGetBindInfo',
'OCIStmtGetPieceInfo',
'OCIStmtPrepare',
'OCIStmtPrepare2',
'OCIStmtRelease',
'OCIStmtSetPieceInfo',
'OCIStringAllocSize',
'OCIStringAssign',
'OCIStringAssignText',
'OCIStringPtr',
'OCIStringResize',
'OCIStringSize',
'OCISvcCtxToLda',
'OCITerminate',
'OCIThreadClose',
'OCIThreadCreate',
'OCIThreadHandleGet',
'OCIThreadHndDestroy',
'OCIThreadHndInit',
'OCIThreadIdDestroy',
'OCIThreadIdGet',
'OCIThreadIdInit',
'OCIThreadIdNull',
'OCIThreadIdSame',
'OCIThreadIdSet',
'OCIThreadIdSetNull',
'OCIThreadInit',
'OCIThreadIsMulti',
'OCIThreadJoin',
'OCIThreadKeyDestroy',
'OCIThreadKeyGet',
'OCIThreadKeyInit',
'OCIThreadKeySet',
'OCIThreadMutexAcquire',
'OCIThreadMutexDestroy',
'OCIThreadMutexInit',
'OCIThreadMutexRelease',
'OCIThreadProcessInit',
'OCIThreadTerm',
'OCITransCommit',
'OCITransDetach',
'OCITransForget',
'OCITransMultiPrepare',
'OCITransPrepare',
'OCITransRollback',
'OCITransStart',
'OCI_GlobalInfo',
'OCI_connPoolTimeoutMon',
'OCI_datetimeSetDate',
'OCI_datetimeSetTime',
'OCI_latfGotGlobal',
'OCI_latfGotGlobalV7',
'OCI_memGetMemCount',
'OCI_number_pDecimalCtx',
'OCI_pEnvList',
'OCI_pGlobalInfo',
'OCI_pLdaList',
'OCI_sthreadsem',
'OCI_sthreadsemV7',
'OCI_sthreadsem_init_flag',
'OCI_sthreadsem_init_flagV7',
'OCI_v7_fMultiThreaded',
'SQLEnvGet',
'SQLSvcCtxGet',
'_LIB_VERSIONIMF']

    from texttable import Texttable
    table = Texttable()
    table.set_deco(Texttable.HEADER)
    table.set_header_align(['l', 'l'])
    table.set_cols_dtype(['t',  # text
                          't'])  # text])
    table.set_cols_align(["l", "l"])
    table.header(["function name", "function pointer"])
    table.set_cols_width([55, 55])

    for func in mylist:
        strlib = "libci64."+func 
        cont = 0
        try:
            my_row = [strlib.ljust(55), getattr(oci, func)]
            table.add_row(my_row)
        except AttributeError:
            cont += 1
            my_row = [strlib.ljust(55), "function not found"]
            table.add_row(my_row)
    mylog.info("\n%s" % table.draw())